sequenceDiagram
    actor User
    User ->> RestController: createPdfReport(reportType, options)
    RestController ->> User: 200 OK
    RestController ->> SchedulerDB: savePdfReportRequest(reportType, options)
    SchedulerThread ->> SchedulerDB: poll
    SchedulerThread ->> PDFService: createPdf(reportType, options)
    PDFService ->> SchedulerThread: pdf
    SchedulerThread ->> EmailService: sendEmail(pdf)